[package]
name = "rs3"
version = "0.1.0"
authors = ["taiyoslime <t@iyosli.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dimacs = "0.2.0"
rand = "*"